Matt5115
chrstphfrtz/litaliano-secondo-il-metodo-natura pull request #3
Opened 2022-09-10 21:16 UTC by matt5115

I created my own branch.  I added the parole.md for ch1 and ch 2. My first time.  I am not sure if I did this properly.

2022-09-10 21:23 UTC, chrstphfrtz commented
Yes, that worked perfectly. The question is: do we need the vocabulary or is there a specific reason we should add them? I guess it would make sense to add translations if people want to print out a page for studying?

2022-09-10 22:25 UTC, matt5115 commented
Yes. That was my thought.  To add translations.  Basically to create one place with all the resources for the book.

2022-09-11 08:41 UTC, chrstphfrtz commented
I see. That makes sense. Could you please create a separate branch + pull request for every topic? Then we can review the changes in smaller chunks.

So basically you need to create two new pull requests. One containing the words from Capitolo 02 and one containing the exercises from Capitolo 02. This one we can use for the words from Capitolo 01.

If you need help with this just let me know!

2022-09-11 15:39 UTC, matt5115 commented
Yes, I will create the separate branch + pull request for every topic.  Sorry, I am new to github

2022-09-12 17:06 UTC, chrstphfrtz requested changes

2022-09-12 17:06 UTC, chrstphfrtz commented on capitolo-01/parole.md
> +bambino,-i
Please format the words like here https://github.com/chrstphfrtz/litaliano-secondo-il-metodo-natura/blob/capitolo-03-parole/capitolo-03/parole-it-en.md

This is what the format looks like in markdown: https://raw.githubusercontent.com/chrstphfrtz/litaliano-secondo-il-metodo-natura/capitolo-03-parole/capitolo-03/parole-it-en.md

The maximum line count per page is 45 so please continue in the 3rd column after line 45.

2022-09-12 19:43 UTC, matt5115 commented on capitolo-01/parole.md
> +bambino,-i
OK, I will work on this.

2022-10-31 12:49 UTC, closed without merging